config/routes.rb
Rails.application.routes.draw do
    root to: 'articles#index'
    get 'signup'  => 'users#new'
    resources :users
    resources :articles do 
        resources :comments, shallow: true
    end
    #trying without nesting/namespacing
    # resources :articles
    # resources :comments
    resources :tags
    
    resources :commits
    
end

app/models/article.rb
class Article < ActiveRecord::Base
    has_many :comments
    has_many :taggings
    has_many :tags, through: :taggings
    belongs_to :user
    has_attached_file :image
    validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]
    def tag_list
        tags.join(", ")
    end
    def tag_list=(tags_string)
        tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
        new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name)}
        self.tags = new_or_found_tags
    end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  belongs_to :user
end

app/models/commit.rb
class Commit < ActiveRecord::Base
     require 'json'
     require 'httparty'
  def self.github_commits(user)
          
      response = HTTParty.get("https://api.github.com/users/#{user}/events/public")
      events = JSON.parse(response.body)
      @commit_messages = []
      @created_at = []
      events.each do |event|
          if event["type"] == "PushEvent"

              @commit_messages << event["payload"]["commits"][0]["message"]
              @created_at << event["created_at"]
                  
          end
      end
      @commit_messages
    end
    
    
    
    
    
    
    
    attr_accessor :result
    def intitialize
        @result = "ten"
    end
    def self.test_method
        "string"
    end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
    has_many :taggings
    has_many :articles, through: :taggings
    
    def to_s
        name
    end
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :article
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :articles
    has_many :comments
    validates :name, :email, presence: true
    validates :name, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i #regex for valid email is publicly available
    validates :email, presence: true, length: { maximum: 150 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    include ArticlesHelper
    #http_basic_authenticate_with name: "mymustard", password: "isbrown12", except: [:index, :show]
    def index
        @articles = Article.all
    end
    
    def show
        @article = Article.find(params[:id])
        @comment = Comment.new
        @comment.article_id = @article_id
    end
    
    def new
        @article = Article.new
    end
    
    def create 
        @article = Article.new(article_params)
        @article.save
        
        flash.notice = "Article '#{@article.title}' Created"
        
        redirect_to article_path(@article)
    end
    
    def destroy
        @article = Article.find(params[:id]).destroy
        
        flash.notice = "Article '#{@article.title}' Deleted"
        redirect_to articles_path
    end
    
    def edit
        @article = Article.find(params[:id])
    end
    
    def update
        @article = Article.find(params[:id])
        @article.update(article_params)
        
        flash.notice = "Article '#{@article.title}' Updated"
        
        redirect_to articles_path(@article)
    end
end

#using this works without a private method because you are explicitly saying the params accepted 
# def create
#   @article = Article.new(
#     title: params[:article][:title],
#     body: params[:article][:body])
#   @article.save
#   redirect_to article_path(@article)
# end

#retrieve user input
#call method with user input

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  #http_basic_authenticate_with name: "mymustard", password: "isbrown12"


  def index
  end
  
  def create
    @comment = Comment.new(comment_params)
    @comment.article_id = params[:article_id]
    
    @article = Article.find(@comment.article_id)
    
    @comment.total = ((@comment.end - @comment.start) / 60 / 60).round(2)
    @comment.save
    if !@comment.end.nil?
      
      
      @article.project_time ||= @comment.total
      @article.project_time += @comment.total
      @article.current_pace = 0
    (@article.comments.where(created_at: (Time.current.midnight)..Time.current.midnight + 1.day)).each {|f| @article.current_pace += f.total }
      
    end
    
    
    

    
    
    
    
    
    
    @article.save
    
    redirect_to article_path(@comment.article)
  end
  
  def destroy
    @comment = Comment.find(params[:id]).destroy
    flash.notice = "Time Record '#{@comment.total}' Deleted"
    @article = Article.find(@comment.article_id)
    @article.update_attribute(:project_time, (@article.project_time - @comment.total) )
    
    @article.current_pace = 0
    (@article.comments.where(created_at: (Time.current.midnight)..Time.current.midnight + 1.day)).each {|f| @article.current_pace += f.total }
    @article.save
    
    redirect_to article_path(@comment.article)
  end
  
  def show
    @comment = Comment.find(params[:id])
  end
  
  def index
  end
  
    def comment_params
      params.require(:comment).permit(:author_name, :body, :start, :end, :total)
    end
end

app/controllers/commits_controller.rb
class CommitsController < ApplicationController
    # include CommitsHelper
    def index
        unless params[:q].nil?

                @commit_messages = Commit.github_commits(params[:q]) #moved to model
                #add the default option is to take it from user login
                

        end
    end
    
    def show

    end
    
    def new
    end
    
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
    #http_basic_authenticate_with name: "mymustard", password: "isbrown12", except: [:index, :show]
    
    def show
        @tag = Tag.find(params[:id])
    end
    
    def index
        @tags = Tag.all
    end

    def destroy
        @tag = Tag.find(params[:id]).destroy
        flash.notice = "Tag '#{@tag.name}' Deleted"
        redirect_to tags_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  def index
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
        redirect_to @user
    else
      render 'new'
    end
    
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
     require 'json'
     require 'httparty'
     def article_params
            params.require(:article).permit(:title, :body, :tag_list, :image, :estimated_time, :est_to_hireable)
     end
     
     def github_commits
          
          response = HTTParty.get('https://api.github.com/users/c1505/events/public')
          my_hash = JSON.parse(response.body)
          @message = []
          my_hash.each do |f|
              if f["type"] == "PushEvent"

                  @message << f["payload"]["commits"][0]["message"]

                  testing_object = "string"
                      
              end
          end
     end
     
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/commits_helper.rb
module CommitsHelper
#      require 'json'
#      require 'httparty'
#   def github_commits(user)
          
#       response = HTTParty.get("https://api.github.com/users/#{user}/events/public")
#       events = JSON.parse(response.body)
#       @commit_messages = []
#       @created_at = []
#       events.each do |event|
#           if event["type"] == "PushEvent"

#               @commit_messages << event["payload"]["commits"][0]["message"]
#               @created_at << event["created_at"]
                  
#           end
#       end
#     end
#     @commit_messages
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/articles/_comment.html.erb
<div>
    <h4>Notes: <%= comment.author_name %></h4>
    <p class="comment">Start: <%= comment.start %></p>
    <p class="comment">End: <%= comment.end %></p>
    <p class="comment">Time Spent: <%= comment.total %> Hours</p>
    <p class="comment"><%= link_to "delete", comment_path(comment.id), method: :delete, data: {confirm: "Really delete the comment?"}%></p>
    
</div>

app/views/articles/_form.html.erb
<%= form_for(@article, html: {multipart: true}) do |f| %>
  <ul>
  <% @article.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
    <p>
    <%= f.label :estimated_time, "Esimated time until minimal viable programmer" %><br />
    <%= f.text_field :estimated_time %>
  </p>
  <p>
    <%= f.label :est_to_hireable, "Esimated time until hireable" %><br />
    <%= f.text_field :est_to_hireable %>
  </p>
  <p>
    <%= f.label :body, "Project Description" %><br />
    <%= f.text_area :body %>
  </p>
  <!--<p>-->
  <!--  <%= f.label :tag_list %><br />-->
  <!--  <%= f.text_field :tag_list %>-->
  <!--</p>-->
  <!--<p>-->
  <!--  <% if @article.image.exists? %>-->
  <!--      <%= image_tag @article.image.url %><br />-->
  <!--  <% end %>-->
  <!--  <%= f.label :image, "Attach an Image" %><br />-->
  <!--  <%= f.file_field :image %>-->
  <!--</p>-->
  <p>
    <%= f.submit %>
  </p>
  <p>

  </p>
<% end %>

app/views/articles/_show.html.erb
<p>
  <audio controls autoplay>
      <source src= "/audio/Extreme Ode to Joy.mp3" type="audio/mpeg">
Your browser does not support the audio element.
   </audio>
</p>
<% @article.update_attribute(:sound_count, @article.project_time) %>

app/views/articles/edit.html.erb
<h1>Edit a Project</h1>

<%= render partial: 'form' %>
    

app/views/articles/index.html.erb
<h1>All Projects</h1>

<ul id="articles">
    <% @articles.each do |article| %>
        <li>
            <%= link_to article.title, article_path(article) %>
        </li>
    <% end %>
</ul>

<%= link_to "Create a New Project", new_article_path, class: "new_article" %>

app/views/articles/new.html.erb
<h1>Create a New Project</h1>
<%= render partial: 'form' %>

app/views/articles/show.html.erb
<h1>Project: <%= @article.title %></h1>
<h2>Hours Complete: <%=@article.project_time %> </h2>
<%if !@article.comments.empty? %>
    <%if @article.comments.last.updated_at.midnight == Time.current.midnight %>
        <h2>Current Pace:<%=@article.current_pace %></h2>
    <% end %>
<%end%>
<%= @message %>
    
      <div class="row">
        <div class="col-md-3">
            <p><u>@current pace</u></p>
            <p><strong><%= (" #{((@article.estimated_time - @article.project_time)/ @article.current_pace ).to_i / 7}   weeks until MVP") unless @article.current_pace == 0 %></strong></p>
            <p><strong><%= (" #{((@article.est_to_hireable - @article.project_time) / @article.current_pace).to_i / 7}  weeks until hireable") unless @article.current_pace == 0 %></strong></p>
        </div>
        <div class="col-md-3">
            <p><u>if one more hour today</u></p>
            <p><strong><%= (" #{((@article.estimated_time - @article.project_time)/ (@article.current_pace + 1) ).to_i / 7}   weeks until MVP") unless @article.current_pace == 0 %></strong></p>
            <p><strong><%= (" #{((@article.est_to_hireable - @article.project_time) / (@article.current_pace + 1)).to_i / 7}  weeks until hireable") unless @article.current_pace == 0 %></strong></p>
        </div>
        <div class="col-md-3">
            <p><u>if 3 hours today</u></p>
            <p><strong><%= (" #{((@article.estimated_time - @article.project_time)/ 3 ).to_i / 7}   weeks until MVP") unless @article.current_pace == 0 %></strong></p>
            <p><strong><%= (" #{((@article.est_to_hireable - @article.project_time) / 3 ).to_i / 7}  weeks until hireable") unless @article.current_pace == 0 %></strong></p>
        </div>
    </div>
      
      
      <div class="row">
        <div class="col-md-3"><%= render partial: 'comments/form' %></div>
        <div class="col-md-3">
        <%if !@article.comments.empty? %>
            <% if @article.comments.last.end.nil? %>
                <%= render partial: 'comments/end' %>
                <% else %>
                <%= render partial: 'comments/form2' %>
                <%end%>
        <%end%>
        </div>
        <div class="col-md-3">
            <p>Estimated hours until MVP: <%=@article.estimated_time - @article.project_time%></p>
<p>Estimated hours until hireable: <%=@article.est_to_hireable - @article.project_time %></p>
        </div>
      </div>

<div class="progress">
  <div class="progress-bar" role="progressbar" aria-valuenow="30" aria-valuemin="0" aria-valuemax="200" style="width: <%=(@article.current_pace / 3) * 100%>%">
    <span class="sr-only">30% Complete</span>
  </div>
</div>




<h3>Logs(<%= @article.comments.size %>)</h3>
<%= render partial: 'articles/comment', collection: @article.comments %>

<p>
    Tags:
    <% @article.tags.each do |tag| %>
        <%= link_to tag.name, tag_path(tag) %>
    <% end %>


<%= render partial: 'show' if (@article.project_time.to_f - 0.99) > (@article.sound_count ||= 1) %>

<%= link_to "<< Back to Articles List", articles_path %>
<%= link_to "delete", article_path(@article), method: :delete, data: {confirm: "Really delete the article?"}%>
<%= link_to "edit", edit_article_path(@article) %>

app/views/comments/_end.html.erb
<h3></h3>
<%= form_for [ @article, @comment ] do |f| %>
    <p class="time_boxes">
        <%= f.label :start, "End Time:" %>
        <%= f.time_select :end, :value => @comment.end, :default => Time.current %>
    </p>
        
        
    <p>
        <%= f.label :author_name, "Note" %><br/>
        <%= f.text_field :author_name%>
    </p>
    <p>
        <%= f.submit 'End', :class => "btn btn-lg btn-primary"%>
        
    </p>
<% end %>
<% @article.comments.last.update_attribute(:end, Time.current) %>

this needs to be updated to just update attribute of the current comment.  now i think it is trying to create a new one

app/views/comments/_form.html.erb
<h3></h3>
<%= form_for [ @article, @comment ] do |f| %>
    <p class="time_boxes">
        <%= f.label :start, "Start Time:" %>
        <%= f.time_select :start, :value => @comment.start, :default => Time.current%>
    </p>   
        
    <p class="time_boxes">
        <%= f.label :start, "End Time:" %>
        <%= f.time_select :end, :value => @comment.end, :default => Time.current + 1.hour %>
    </p>
        
        
    <p>
        <%= f.label :author_name, "Note" %><br/>
        <%= f.text_field :author_name %>
    </p>
    <p>
        <%= f.submit 'Submit', :class => "btn btn-lg btn-primary"%>
        
    </p>
<% end %>

app/views/comments/_form2.html.erb
<h3></h3>
<%= form_for [ @article, @comment ] do |f| %>
    <p class="time_boxes">
        <%= f.label :start, "Start Time:" %>
        <%= f.time_select :start, :value => @comment.start, :default => Time.current%>
    </p>   
    <p>
        <%= f.submit 'Start', :class => "btn btn-lg btn-primary"%>
        
    </p>
<% end %>

app/views/comments/edit.html.erb
<h1>Edit an time record</h1>

<%= render partial: 'form' %>

app/views/comments/show.html.erb
<%= @comment.article_id %>
<%= Comment.last.article_id %>
<%= link_to "delete", comment_path(@comment), method: :delete, data: {confirm: "Really delete the comment?"}%>

app/views/commits/index.html.erb
<%= form_tag("/commits", method: "get") do %>
  <%= label_tag(:q, "Search for:") %>
  <%= text_field_tag(:q) %>
  <%= submit_tag("Search") %>


<% end %>

<% unless params[:q].nil? %>
  <h1><%=params[:q]%> Commit messages</h1>

    <% @commit_messages.each do |f| %>
    <ul><%= f %></ul>
    <%end%>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blogger</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
  
  <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "Time App", articles_path, id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home",   articles_path %></li>
            <li><%= link_to "New Project", new_article_path%></li>
            <li><%= link_to "Raptorize!", users_path%></li>
            <li><%= link_to "Github Activity", commits_path%></li>
          </ul>
        </nav>
      </div>
    </header>
    <div>
      
    </div>
    <div class="container">
      <%= yield %>
    </div>
    <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
</body>
</html>


<!-- app/views/layouts/application.html.erb -->

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/tags/index.html.erb
<h1>Article Tags</h1>
<% @tags.each do |f| %>
    <%= link_to f.name, tag_path(f) %>
<% end %>

app/views/tags/show.html.erb
<h1> Articles Tagged with <%= @tag.name %></h1>

<ul>
    <%= @tag.articles.each do |article| %>
        <li><%= link_to article.title, article_path(article) %></li>
    <% end %>
</ul>
<%= link_to "delete", tag_path(@tag), method: :delete, data: {confirm: "Really delete the tag?"}%>

app/views/users/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<title>Title This Page :)</title>
	
	<!-- jQuery: Grab Google CDN jQuery. fall back to local if necessary -->
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
	<script>!window.jQuery && document.write('<script src="jquery-1.4.1.min.js"><\/script>')</script>
	
	<!-- The raptorize file  -->
	<script src="jquery.raptorize.1.0.js"></script>
	
	<!-- For the button version -->
	<script type="text/javascript">
		$(window).load('page:load',function() {
			$('.button').raptorize();
		});
	</script>
	
	<!-- For the Konami Code version -->
	<script type="text/javascript">
		$(window).load(function() {
			$('.button').raptorize({
				'enterOn' : 'konami-code'
			});
		});
	</script>
	<!--when accessing from url click button does not work either.  page:load used because of turbolinkds-->
	 <script type="text/javascript">
		$(window).load('page:load', function() {
			$('.button').raptorize({
				'enterOn' : 'timer',
				'delayTime' : 2000
			});
		});
	</script>	

</head>
<body>
	<h1>Hey There!</h1>
	
	<p><a href="#" class="button">Click me</a> to activate the Raptorize plugin.</p>
	<p>You can also use the Konami-Code (on your keyboard type &uarr; &uarr; &darr; &darr; &larr; &rarr; &larr; &rarr; B A)</p>
	
</body>
</html>

app/views/users/new.html.erb
<h1>User#new</h1>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form_control' %>
        
        <%= f.label :email %>
        <%= f.text_field :email, class: 'form_control' %>
        
        <%= f.label :password %>
        <%= f.password_field :password, class: 'form_control' %>
        
        <%= f.label :password_confirmation, "Confirmation"  %>
        <%= f.password_field :password_confirmation, class: 'form_control' %>
        
        <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
    </div>
</div>


    
    
    

app/views/users/show.html.erb
<p><%= @user.name %></p>
<p><%= @user.email %></p>